# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawOrganizationClient, RawOrganizationClient

if typing.TYPE_CHECKING:
    from .configuration.client import AsyncConfigurationClient, ConfigurationClient
    from .domains.client import AsyncDomainsClient, DomainsClient
    from .identity_providers.client import AsyncIdentityProvidersClient, IdentityProvidersClient


class OrganizationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._configuration: typing.Optional[ConfigurationClient] = None
        self._domains: typing.Optional[DomainsClient] = None
        self._identity_providers: typing.Optional[IdentityProvidersClient] = None

    @property
    def with_raw_response(self) -> RawOrganizationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationClient
        """
        return self._raw_client

    @property
    def configuration(self):
        if self._configuration is None:
            from .configuration.client import ConfigurationClient  # noqa: E402

            self._configuration = ConfigurationClient(client_wrapper=self._client_wrapper)
        return self._configuration

    @property
    def domains(self):
        if self._domains is None:
            from .domains.client import DomainsClient  # noqa: E402

            self._domains = DomainsClient(client_wrapper=self._client_wrapper)
        return self._domains

    @property
    def identity_providers(self):
        if self._identity_providers is None:
            from .identity_providers.client import IdentityProvidersClient  # noqa: E402

            self._identity_providers = IdentityProvidersClient(client_wrapper=self._client_wrapper)
        return self._identity_providers


class AsyncOrganizationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._configuration: typing.Optional[AsyncConfigurationClient] = None
        self._domains: typing.Optional[AsyncDomainsClient] = None
        self._identity_providers: typing.Optional[AsyncIdentityProvidersClient] = None

    @property
    def with_raw_response(self) -> AsyncRawOrganizationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationClient
        """
        return self._raw_client

    @property
    def configuration(self):
        if self._configuration is None:
            from .configuration.client import AsyncConfigurationClient  # noqa: E402

            self._configuration = AsyncConfigurationClient(client_wrapper=self._client_wrapper)
        return self._configuration

    @property
    def domains(self):
        if self._domains is None:
            from .domains.client import AsyncDomainsClient  # noqa: E402

            self._domains = AsyncDomainsClient(client_wrapper=self._client_wrapper)
        return self._domains

    @property
    def identity_providers(self):
        if self._identity_providers is None:
            from .identity_providers.client import AsyncIdentityProvidersClient  # noqa: E402

            self._identity_providers = AsyncIdentityProvidersClient(client_wrapper=self._client_wrapper)
        return self._identity_providers
