# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.org_domain_id import OrgDomainId
from ....types.start_organization_domain_verification_response_content import (
    StartOrganizationDomainVerificationResponseContent,
)
from .raw_client import AsyncRawVerifyClient, RawVerifyClient


class VerifyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVerifyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVerifyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVerifyClient
        """
        return self._raw_client

    def create(
        self, domain_id: OrgDomainId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StartOrganizationDomainVerificationResponseContent:
        """
        Initiate the verification process for a domain specified by ID for this Organization.

        Parameters
        ----------
        domain_id : OrgDomainId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartOrganizationDomainVerificationResponseContent
            Organization domain verification successfully started.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.domains.verify.create(
            domain_id="domain_id",
        )
        """
        _response = self._raw_client.create(domain_id, request_options=request_options)
        return _response.data


class AsyncVerifyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVerifyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVerifyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVerifyClient
        """
        return self._raw_client

    async def create(
        self, domain_id: OrgDomainId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StartOrganizationDomainVerificationResponseContent:
        """
        Initiate the verification process for a domain specified by ID for this Organization.

        Parameters
        ----------
        domain_id : OrgDomainId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartOrganizationDomainVerificationResponseContent
            Organization domain verification successfully started.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.domains.verify.create(
                domain_id="domain_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(domain_id, request_options=request_options)
        return _response.data
