# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.create_id_p_provisioning_config_response_content import CreateIdPProvisioningConfigResponseContent
from ....types.get_id_p_provisioning_config_response_content import GetIdPProvisioningConfigResponseContent
from ....types.idp_id import IdpId
from .raw_client import AsyncRawProvisioningClient, RawProvisioningClient

if typing.TYPE_CHECKING:
    from .scim_tokens.client import AsyncScimTokensClient, ScimTokensClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProvisioningClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProvisioningClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._scim_tokens: typing.Optional[ScimTokensClient] = None

    @property
    def with_raw_response(self) -> RawProvisioningClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProvisioningClient
        """
        return self._raw_client

    def get(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIdPProvisioningConfigResponseContent:
        """
        Retrieve the Provisioning Configuration for an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdPProvisioningConfigResponseContent
            Provisioning config successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.get(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.get(idp_id, request_options=request_options)
        return _response.data

    def create(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateIdPProvisioningConfigResponseContent:
        """
        Create a new Provisioning Configuration for an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdPProvisioningConfigResponseContent
            Provisioning configuration successfully created.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.create(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.create(idp_id, request_options=request_options)
        return _response.data

    def delete(self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete the Provisioning Configuration for an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.delete(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.delete(idp_id, request_options=request_options)
        return _response.data

    def update_attributes(
        self,
        idp_id: IdpId,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetIdPProvisioningConfigResponseContent:
        """
        Refresh the attribute mapping for the Provisioning Configuration of an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.

        Parameters
        ----------
        idp_id : IdpId

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdPProvisioningConfigResponseContent
            Provisioning config successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.update_attributes(
            idp_id="idp_id",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.update_attributes(idp_id, request=request, request_options=request_options)
        return _response.data

    @property
    def scim_tokens(self):
        if self._scim_tokens is None:
            from .scim_tokens.client import ScimTokensClient  # noqa: E402

            self._scim_tokens = ScimTokensClient(client_wrapper=self._client_wrapper)
        return self._scim_tokens


class AsyncProvisioningClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProvisioningClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._scim_tokens: typing.Optional[AsyncScimTokensClient] = None

    @property
    def with_raw_response(self) -> AsyncRawProvisioningClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProvisioningClient
        """
        return self._raw_client

    async def get(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIdPProvisioningConfigResponseContent:
        """
        Retrieve the Provisioning Configuration for an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdPProvisioningConfigResponseContent
            Provisioning config successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.get(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(idp_id, request_options=request_options)
        return _response.data

    async def create(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateIdPProvisioningConfigResponseContent:
        """
        Create a new Provisioning Configuration for an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdPProvisioningConfigResponseContent
            Provisioning configuration successfully created.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.create(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(idp_id, request_options=request_options)
        return _response.data

    async def delete(self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete the Provisioning Configuration for an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.delete(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(idp_id, request_options=request_options)
        return _response.data

    async def update_attributes(
        self,
        idp_id: IdpId,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetIdPProvisioningConfigResponseContent:
        """
        Refresh the attribute mapping for the Provisioning Configuration of an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.

        Parameters
        ----------
        idp_id : IdpId

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdPProvisioningConfigResponseContent
            Provisioning config successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.update_attributes(
                idp_id="idp_id",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_attributes(idp_id, request=request, request_options=request_options)
        return _response.data

    @property
    def scim_tokens(self):
        if self._scim_tokens is None:
            from .scim_tokens.client import AsyncScimTokensClient  # noqa: E402

            self._scim_tokens = AsyncScimTokensClient(client_wrapper=self._client_wrapper)
        return self._scim_tokens
