# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.create_member_invitation_invitee import CreateMemberInvitationInvitee
from ...types.create_member_invitation_response_content import CreateMemberInvitationResponseContent
from ...types.get_member_invitation_response_content import GetMemberInvitationResponseContent
from ...types.invitation_id import InvitationId
from ...types.list_members_invitations_response_content import ListMembersInvitationsResponseContent
from ...types.member_invitation import MemberInvitation
from ...types.member_invitation_inviter import MemberInvitationInviter
from .raw_client import AsyncRawInvitationsClient, RawInvitationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InvitationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInvitationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInvitationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInvitationsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        fields: typing.Optional[str] = None,
        include_fields: typing.Optional[bool] = True,
        from_: typing.Optional[str] = None,
        take: typing.Optional[int] = 50,
        sort: typing.Optional[str] = "created_at:-1",
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[MemberInvitation, ListMembersInvitationsResponseContent]:
        """
        Retrieve a list of all member invitations for this Organization.

        Parameters
        ----------
        fields : typing.Optional[str]
            Comma-separated list of fields to include or exclude (based on value provided for include_fields) in the result. Leave empty to retrieve all fields. Note: you cannot filter on ticket_id and this value will only be returned when fields are not filtered.

        include_fields : typing.Optional[bool]
            Whether specified fields are to be included (true) or excluded (false). Defaults to true

        from_ : typing.Optional[str]
            An optional cursor from which to start the selection (exclusive).

        take : typing.Optional[int]
            Number of results per page. Defaults to 50.

        sort : typing.Optional[str]
            Field to sort by. Use field:order where order is 1 for ascending and -1 for descending. Defaults to created_at:-1

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[MemberInvitation, ListMembersInvitationsResponseContent]
            List Members Invitations for an Organization.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        response = client.organization.invitations.list(
            fields="fields",
            include_fields=True,
            from_="from",
            take=1,
            sort="sort",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            fields=fields,
            include_fields=include_fields,
            from_=from_,
            take=take,
            sort=sort,
            request_options=request_options,
        )

    def create(
        self,
        *,
        invitees: typing.Sequence[CreateMemberInvitationInvitee],
        auth_0_custom_domain: typing.Optional[str] = None,
        inviter: typing.Optional[MemberInvitationInviter] = OMIT,
        identity_provider_id: typing.Optional[str] = OMIT,
        ttl_sec: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMemberInvitationResponseContent:
        """
        Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.

        Parameters
        ----------
        invitees : typing.Sequence[CreateMemberInvitationInvitee]

        auth_0_custom_domain : typing.Optional[str]

        inviter : typing.Optional[MemberInvitationInviter]

        identity_provider_id : typing.Optional[str]
            Identity provider identifier.

        ttl_sec : typing.Optional[int]
            Number of seconds for which the invitation is valid before expiration. If unspecified or set to 0, this value defaults to 604800 seconds (7 days). Max value: 2592000 seconds (30 days).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMemberInvitationResponseContent
            Create Member Invitations for an Organization.

        Examples
        --------
        from auth0 import Auth0, CreateMemberInvitationInvitee, MemberInvitationInviter

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.invitations.create(
            invitees=[
                CreateMemberInvitationInvitee(
                    email="user@example.com",
                    roles=["rol_0000000000000001"],
                )
            ],
            inviter=MemberInvitationInviter(
                name="Allison the Admin",
            ),
            identity_provider_id="con_2CZPv6IY0gWzDaQJ",
            ttl_sec=3600,
        )
        """
        _response = self._raw_client.create(
            invitees=invitees,
            auth_0_custom_domain=auth_0_custom_domain,
            inviter=inviter,
            identity_provider_id=identity_provider_id,
            ttl_sec=ttl_sec,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        invitation_id: InvitationId,
        *,
        fields: typing.Optional[str] = None,
        include_fields: typing.Optional[bool] = True,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetMemberInvitationResponseContent:
        """
        Retrieve details of a member invitation specified by ID for this Organization.

        Parameters
        ----------
        invitation_id : InvitationId

        fields : typing.Optional[str]
            Comma-separated list of fields to include or exclude (based on value provided for include_fields) in the result. Leave empty to retrieve all fields. Note: you cannot filter on ticket_id and this value will only be returned when fields are not filtered.

        include_fields : typing.Optional[bool]
            Whether specified fields are to be included (true) or excluded (false). Defaults to true

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMemberInvitationResponseContent
            Get Member Invitation for an Organization by Id.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.invitations.get(
            invitation_id="invitation_id",
            fields="fields",
            include_fields=True,
        )
        """
        _response = self._raw_client.get(
            invitation_id, fields=fields, include_fields=include_fields, request_options=request_options
        )
        return _response.data

    def delete(self, invitation_id: InvitationId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revoke a member invitation specified by ID for this Organization.

        Parameters
        ----------
        invitation_id : InvitationId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.invitations.delete(
            invitation_id="invitation_id",
        )
        """
        _response = self._raw_client.delete(invitation_id, request_options=request_options)
        return _response.data


class AsyncInvitationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInvitationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInvitationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInvitationsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        fields: typing.Optional[str] = None,
        include_fields: typing.Optional[bool] = True,
        from_: typing.Optional[str] = None,
        take: typing.Optional[int] = 50,
        sort: typing.Optional[str] = "created_at:-1",
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[MemberInvitation, ListMembersInvitationsResponseContent]:
        """
        Retrieve a list of all member invitations for this Organization.

        Parameters
        ----------
        fields : typing.Optional[str]
            Comma-separated list of fields to include or exclude (based on value provided for include_fields) in the result. Leave empty to retrieve all fields. Note: you cannot filter on ticket_id and this value will only be returned when fields are not filtered.

        include_fields : typing.Optional[bool]
            Whether specified fields are to be included (true) or excluded (false). Defaults to true

        from_ : typing.Optional[str]
            An optional cursor from which to start the selection (exclusive).

        take : typing.Optional[int]
            Number of results per page. Defaults to 50.

        sort : typing.Optional[str]
            Field to sort by. Use field:order where order is 1 for ascending and -1 for descending. Defaults to created_at:-1

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[MemberInvitation, ListMembersInvitationsResponseContent]
            List Members Invitations for an Organization.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.organization.invitations.list(
                fields="fields",
                include_fields=True,
                from_="from",
                take=1,
                sort="sort",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            fields=fields,
            include_fields=include_fields,
            from_=from_,
            take=take,
            sort=sort,
            request_options=request_options,
        )

    async def create(
        self,
        *,
        invitees: typing.Sequence[CreateMemberInvitationInvitee],
        auth_0_custom_domain: typing.Optional[str] = None,
        inviter: typing.Optional[MemberInvitationInviter] = OMIT,
        identity_provider_id: typing.Optional[str] = OMIT,
        ttl_sec: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMemberInvitationResponseContent:
        """
        Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.

        Parameters
        ----------
        invitees : typing.Sequence[CreateMemberInvitationInvitee]

        auth_0_custom_domain : typing.Optional[str]

        inviter : typing.Optional[MemberInvitationInviter]

        identity_provider_id : typing.Optional[str]
            Identity provider identifier.

        ttl_sec : typing.Optional[int]
            Number of seconds for which the invitation is valid before expiration. If unspecified or set to 0, this value defaults to 604800 seconds (7 days). Max value: 2592000 seconds (30 days).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMemberInvitationResponseContent
            Create Member Invitations for an Organization.

        Examples
        --------
        import asyncio

        from auth0 import (
            AsyncAuth0,
            CreateMemberInvitationInvitee,
            MemberInvitationInviter,
        )

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.invitations.create(
                invitees=[
                    CreateMemberInvitationInvitee(
                        email="user@example.com",
                        roles=["rol_0000000000000001"],
                    )
                ],
                inviter=MemberInvitationInviter(
                    name="Allison the Admin",
                ),
                identity_provider_id="con_2CZPv6IY0gWzDaQJ",
                ttl_sec=3600,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            invitees=invitees,
            auth_0_custom_domain=auth_0_custom_domain,
            inviter=inviter,
            identity_provider_id=identity_provider_id,
            ttl_sec=ttl_sec,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        invitation_id: InvitationId,
        *,
        fields: typing.Optional[str] = None,
        include_fields: typing.Optional[bool] = True,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetMemberInvitationResponseContent:
        """
        Retrieve details of a member invitation specified by ID for this Organization.

        Parameters
        ----------
        invitation_id : InvitationId

        fields : typing.Optional[str]
            Comma-separated list of fields to include or exclude (based on value provided for include_fields) in the result. Leave empty to retrieve all fields. Note: you cannot filter on ticket_id and this value will only be returned when fields are not filtered.

        include_fields : typing.Optional[bool]
            Whether specified fields are to be included (true) or excluded (false). Defaults to true

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMemberInvitationResponseContent
            Get Member Invitation for an Organization by Id.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.invitations.get(
                invitation_id="invitation_id",
                fields="fields",
                include_fields=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            invitation_id, fields=fields, include_fields=include_fields, request_options=request_options
        )
        return _response.data

    async def delete(
        self, invitation_id: InvitationId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Revoke a member invitation specified by ID for this Organization.

        Parameters
        ----------
        invitation_id : InvitationId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.invitations.delete(
                invitation_id="invitation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(invitation_id, request_options=request_options)
        return _response.data
