# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.get_configuration_response_content import GetConfigurationResponseContent
from .raw_client import AsyncRawConfigurationClient, RawConfigurationClient

if typing.TYPE_CHECKING:
    from .identity_providers.client import AsyncIdentityProvidersClient, IdentityProvidersClient


class ConfigurationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConfigurationClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._identity_providers: typing.Optional[IdentityProvidersClient] = None

    @property
    def with_raw_response(self) -> RawConfigurationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConfigurationClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetConfigurationResponseContent:
        """
        Retrieve the configuration for the /my-org API. This will return all stored client information with the exception of attributes that are identifiers. Identifier attributes will be given their own endpoint that will return the full object. This will give the components all of the information they will need to be successful. The SDK provider for the components should manage fetching and caching this information for all components.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetConfigurationResponseContent
            Configuration successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.configuration.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    @property
    def identity_providers(self):
        if self._identity_providers is None:
            from .identity_providers.client import IdentityProvidersClient  # noqa: E402

            self._identity_providers = IdentityProvidersClient(client_wrapper=self._client_wrapper)
        return self._identity_providers


class AsyncConfigurationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConfigurationClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._identity_providers: typing.Optional[AsyncIdentityProvidersClient] = None

    @property
    def with_raw_response(self) -> AsyncRawConfigurationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConfigurationClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetConfigurationResponseContent:
        """
        Retrieve the configuration for the /my-org API. This will return all stored client information with the exception of attributes that are identifiers. Identifier attributes will be given their own endpoint that will return the full object. This will give the components all of the information they will need to be successful. The SDK provider for the components should manage fetching and caching this information for all components.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetConfigurationResponseContent
            Configuration successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.configuration.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    @property
    def identity_providers(self):
        if self._identity_providers is None:
            from .identity_providers.client import AsyncIdentityProvidersClient  # noqa: E402

            self._identity_providers = AsyncIdentityProvidersClient(client_wrapper=self._client_wrapper)
        return self._identity_providers
