# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.create_organization_domain_response_content import CreateOrganizationDomainResponseContent
from ...types.get_organization_domain_response_content import GetOrganizationDomainResponseContent
from ...types.list_organization_domains_response_content import ListOrganizationDomainsResponseContent
from ...types.org_domain import OrgDomain
from ...types.org_domain_id import OrgDomainId
from ...types.org_domain_name import OrgDomainName
from .raw_client import AsyncRawDomainsClient, RawDomainsClient

if typing.TYPE_CHECKING:
    from .identity_providers.client import AsyncIdentityProvidersClient, IdentityProvidersClient
    from .verify.client import AsyncVerifyClient, VerifyClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DomainsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDomainsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._verify: typing.Optional[VerifyClient] = None
        self._identity_providers: typing.Optional[IdentityProvidersClient] = None

    @property
    def with_raw_response(self) -> RawDomainsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDomainsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        from_: typing.Optional[str] = None,
        take: typing.Optional[int] = 50,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[OrgDomain, ListOrganizationDomainsResponseContent]:
        """
        Retrieve a list of all pending and verified domains for this Organization.

        Parameters
        ----------
        from_ : typing.Optional[str]
            An optional cursor from which to start the selection (exclusive).

        take : typing.Optional[int]
            Number of results per page. Defaults to 50.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[OrgDomain, ListOrganizationDomainsResponseContent]
            List domains for an organization.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        response = client.organization.domains.list(
            from_="from",
            take=1,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(from_=from_, take=take, request_options=request_options)

    def create(
        self, *, domain: OrgDomainName, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateOrganizationDomainResponseContent:
        """
        Create a new domain for this Organization.

        Parameters
        ----------
        domain : OrgDomainName

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOrganizationDomainResponseContent
            Domain successfully created for organization.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.domains.create(
            domain="acme.com",
        )
        """
        _response = self._raw_client.create(domain=domain, request_options=request_options)
        return _response.data

    def get(
        self, domain_id: OrgDomainId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrganizationDomainResponseContent:
        """
        Retrieve details of a domain specified by ID for this Organization.

        Parameters
        ----------
        domain_id : OrgDomainId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrganizationDomainResponseContent
            Organization domain successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.domains.get(
            domain_id="domain_id",
        )
        """
        _response = self._raw_client.get(domain_id, request_options=request_options)
        return _response.data

    def delete(self, domain_id: OrgDomainId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a domain specified by ID from this Organization.

        Parameters
        ----------
        domain_id : OrgDomainId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.domains.delete(
            domain_id="domain_id",
        )
        """
        _response = self._raw_client.delete(domain_id, request_options=request_options)
        return _response.data

    @property
    def verify(self):
        if self._verify is None:
            from .verify.client import VerifyClient  # noqa: E402

            self._verify = VerifyClient(client_wrapper=self._client_wrapper)
        return self._verify

    @property
    def identity_providers(self):
        if self._identity_providers is None:
            from .identity_providers.client import IdentityProvidersClient  # noqa: E402

            self._identity_providers = IdentityProvidersClient(client_wrapper=self._client_wrapper)
        return self._identity_providers


class AsyncDomainsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDomainsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._verify: typing.Optional[AsyncVerifyClient] = None
        self._identity_providers: typing.Optional[AsyncIdentityProvidersClient] = None

    @property
    def with_raw_response(self) -> AsyncRawDomainsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDomainsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        from_: typing.Optional[str] = None,
        take: typing.Optional[int] = 50,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[OrgDomain, ListOrganizationDomainsResponseContent]:
        """
        Retrieve a list of all pending and verified domains for this Organization.

        Parameters
        ----------
        from_ : typing.Optional[str]
            An optional cursor from which to start the selection (exclusive).

        take : typing.Optional[int]
            Number of results per page. Defaults to 50.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[OrgDomain, ListOrganizationDomainsResponseContent]
            List domains for an organization.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.organization.domains.list(
                from_="from",
                take=1,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(from_=from_, take=take, request_options=request_options)

    async def create(
        self, *, domain: OrgDomainName, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateOrganizationDomainResponseContent:
        """
        Create a new domain for this Organization.

        Parameters
        ----------
        domain : OrgDomainName

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOrganizationDomainResponseContent
            Domain successfully created for organization.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.domains.create(
                domain="acme.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(domain=domain, request_options=request_options)
        return _response.data

    async def get(
        self, domain_id: OrgDomainId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrganizationDomainResponseContent:
        """
        Retrieve details of a domain specified by ID for this Organization.

        Parameters
        ----------
        domain_id : OrgDomainId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrganizationDomainResponseContent
            Organization domain successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.domains.get(
                domain_id="domain_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(domain_id, request_options=request_options)
        return _response.data

    async def delete(self, domain_id: OrgDomainId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a domain specified by ID from this Organization.

        Parameters
        ----------
        domain_id : OrgDomainId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.domains.delete(
                domain_id="domain_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(domain_id, request_options=request_options)
        return _response.data

    @property
    def verify(self):
        if self._verify is None:
            from .verify.client import AsyncVerifyClient  # noqa: E402

            self._verify = AsyncVerifyClient(client_wrapper=self._client_wrapper)
        return self._verify

    @property
    def identity_providers(self):
        if self._identity_providers is None:
            from .identity_providers.client import AsyncIdentityProvidersClient  # noqa: E402

            self._identity_providers = AsyncIdentityProvidersClient(client_wrapper=self._client_wrapper)
        return self._identity_providers
