# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.get_organization_details_response_content import GetOrganizationDetailsResponseContent
from ..types.org_branding import OrgBranding
from ..types.org_third_party_client_access_enum import OrgThirdPartyClientAccessEnum
from ..types.update_organization_details_response_content import UpdateOrganizationDetailsResponseContent
from .raw_client import AsyncRawOrganizationDetailsClient, RawOrganizationDetailsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrganizationDetailsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationDetailsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrganizationDetailsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationDetailsClient
        """
        return self._raw_client

    def delete(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently delete this Organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization_details.delete()
        """
        _response = self._raw_client.delete(request_options=request_options)
        return _response.data

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetOrganizationDetailsResponseContent:
        """
        Retrieve details for this Organization, including display name and branding options. To learn more about Auth0 Organizations, read [Organizations](https://auth0.com/docs/manage-users/organizations).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrganizationDetailsResponseContent
            Organization details successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization_details.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def update(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        branding: typing.Optional[OrgBranding] = OMIT,
        third_party_client_access: typing.Optional[OrgThirdPartyClientAccessEnum] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateOrganizationDetailsResponseContent:
        """
        Update details for this Organization, such as display name and branding options. To learn more about Auth0 Organizations, read [Organizations](https://auth0.com/docs/manage-users/organizations).

        Parameters
        ----------
        name : typing.Optional[str]
            The name of this organization.

        display_name : typing.Optional[str]
            Friendly name of this organization.

        branding : typing.Optional[OrgBranding]

        third_party_client_access : typing.Optional[OrgThirdPartyClientAccessEnum]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateOrganizationDetailsResponseContent
            Organization details successfully retrieved.

        Examples
        --------
        from auth0 import Auth0, OrgBranding, OrgBrandingColors

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization_details.update(
            name="testorg",
            display_name="Test Organization",
            branding=OrgBranding(
                logo_url="https://example.com/logo.png",
                colors=OrgBrandingColors(
                    primary="#000000",
                    page_background="#FFFFFF",
                ),
            ),
        )
        """
        _response = self._raw_client.update(
            name=name,
            display_name=display_name,
            branding=branding,
            third_party_client_access=third_party_client_access,
            request_options=request_options,
        )
        return _response.data


class AsyncOrganizationDetailsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationDetailsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrganizationDetailsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationDetailsClient
        """
        return self._raw_client

    async def delete(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently delete this Organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization_details.delete()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(request_options=request_options)
        return _response.data

    async def get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrganizationDetailsResponseContent:
        """
        Retrieve details for this Organization, including display name and branding options. To learn more about Auth0 Organizations, read [Organizations](https://auth0.com/docs/manage-users/organizations).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrganizationDetailsResponseContent
            Organization details successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization_details.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def update(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        branding: typing.Optional[OrgBranding] = OMIT,
        third_party_client_access: typing.Optional[OrgThirdPartyClientAccessEnum] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateOrganizationDetailsResponseContent:
        """
        Update details for this Organization, such as display name and branding options. To learn more about Auth0 Organizations, read [Organizations](https://auth0.com/docs/manage-users/organizations).

        Parameters
        ----------
        name : typing.Optional[str]
            The name of this organization.

        display_name : typing.Optional[str]
            Friendly name of this organization.

        branding : typing.Optional[OrgBranding]

        third_party_client_access : typing.Optional[OrgThirdPartyClientAccessEnum]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateOrganizationDetailsResponseContent
            Organization details successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0, OrgBranding, OrgBrandingColors

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization_details.update(
                name="testorg",
                display_name="Test Organization",
                branding=OrgBranding(
                    logo_url="https://example.com/logo.png",
                    colors=OrgBrandingColors(
                        primary="#000000",
                        page_background="#FFFFFF",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            name=name,
            display_name=display_name,
            branding=branding,
            third_party_client_access=third_party_client_access,
            request_options=request_options,
        )
        return _response.data
