# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.pagination import AsyncPager, SyncPager
from ....core.request_options import RequestOptions
from ....types.get_organization_member_roles_response_content import GetOrganizationMemberRolesResponseContent
from ....types.org_member_id import OrgMemberId
from ....types.role import Role
from ....types.role_id import RoleId
from .raw_client import AsyncRawRolesClient, RawRolesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RolesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRolesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRolesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRolesClient
        """
        return self._raw_client

    def list(
        self,
        user_id: OrgMemberId,
        *,
        from_: typing.Optional[str] = None,
        take: typing.Optional[int] = 50,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Role, GetOrganizationMemberRolesResponseContent]:
        """
        Retrieve a list of roles assigned to a member specified by ID for this Organization.

        Parameters
        ----------
        user_id : OrgMemberId

        from_ : typing.Optional[str]
            An optional cursor from which to start the selection (exclusive).

        take : typing.Optional[int]
            Number of results per page. Defaults to 50.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Role, GetOrganizationMemberRolesResponseContent]
            Retrieved memeber roles successfully.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        response = client.organization.members.roles.list(
            user_id="user_id",
            from_="from",
            take=1,
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(user_id, from_=from_, take=take, request_options=request_options)

    def assign(
        self,
        user_id: OrgMemberId,
        *,
        role_ids: typing.Sequence[RoleId],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Assign roles to a member specified by ID for this Organization.

        Parameters
        ----------
        user_id : OrgMemberId

        role_ids : typing.Sequence[RoleId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.members.roles.assign(
            user_id="user_id",
            role_ids=["rol_SO2j0sFo9NFa3F9w"],
        )
        """
        _response = self._raw_client.assign(user_id, role_ids=role_ids, request_options=request_options)
        return _response.data

    def unassign(
        self,
        user_id: OrgMemberId,
        *,
        role_ids: typing.Sequence[RoleId],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Remove roles from a member specified by ID for this Organization.

        Parameters
        ----------
        user_id : OrgMemberId

        role_ids : typing.Sequence[RoleId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.members.roles.unassign(
            user_id="user_id",
            role_ids=["rol_SO2j0sFo9NFa3F9w"],
        )
        """
        _response = self._raw_client.unassign(user_id, role_ids=role_ids, request_options=request_options)
        return _response.data


class AsyncRolesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRolesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRolesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRolesClient
        """
        return self._raw_client

    async def list(
        self,
        user_id: OrgMemberId,
        *,
        from_: typing.Optional[str] = None,
        take: typing.Optional[int] = 50,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Role, GetOrganizationMemberRolesResponseContent]:
        """
        Retrieve a list of roles assigned to a member specified by ID for this Organization.

        Parameters
        ----------
        user_id : OrgMemberId

        from_ : typing.Optional[str]
            An optional cursor from which to start the selection (exclusive).

        take : typing.Optional[int]
            Number of results per page. Defaults to 50.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Role, GetOrganizationMemberRolesResponseContent]
            Retrieved memeber roles successfully.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.organization.members.roles.list(
                user_id="user_id",
                from_="from",
                take=1,
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(user_id, from_=from_, take=take, request_options=request_options)

    async def assign(
        self,
        user_id: OrgMemberId,
        *,
        role_ids: typing.Sequence[RoleId],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Assign roles to a member specified by ID for this Organization.

        Parameters
        ----------
        user_id : OrgMemberId

        role_ids : typing.Sequence[RoleId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.members.roles.assign(
                user_id="user_id",
                role_ids=["rol_SO2j0sFo9NFa3F9w"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assign(user_id, role_ids=role_ids, request_options=request_options)
        return _response.data

    async def unassign(
        self,
        user_id: OrgMemberId,
        *,
        role_ids: typing.Sequence[RoleId],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Remove roles from a member specified by ID for this Organization.

        Parameters
        ----------
        user_id : OrgMemberId

        role_ids : typing.Sequence[RoleId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.members.roles.unassign(
                user_id="user_id",
                role_ids=["rol_SO2j0sFo9NFa3F9w"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unassign(user_id, role_ids=role_ids, request_options=request_options)
        return _response.data
