# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_user_stores_response_content import ListUserStoresResponseContent
from ...types.organization_access_level_enum import OrganizationAccessLevelEnum
from .raw_client import AsyncRawUserStoresClient, RawUserStoresClient


class UserStoresClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserStoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserStoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserStoresClient
        """
        return self._raw_client

    def list(
        self,
        *,
        member_access_level: typing.Optional[
            typing.Union[OrganizationAccessLevelEnum, typing.Sequence[OrganizationAccessLevelEnum]]
        ] = None,
        is_enabled: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserStoresResponseContent:
        """
        Retrieve the user stores for the associated Organization.

        Parameters
        ----------
        member_access_level : typing.Optional[typing.Union[OrganizationAccessLevelEnum, typing.Sequence[OrganizationAccessLevelEnum]]]
            When present, only connections whose Organization Member Access Level matches one of the provided values are returned. Accepted values are full, limited, readonly and none.

        is_enabled : typing.Optional[bool]
            Filter the returned list by enabled status. When `true`, only enabled items are returned; when `false`, only disabled items; when omitted, all items are returned.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserStoresResponseContent
            Retrieve user stores for an Organization.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.user_stores.list(
            member_access_level=["none"],
            is_enabled=True,
        )
        """
        _response = self._raw_client.list(
            member_access_level=member_access_level, is_enabled=is_enabled, request_options=request_options
        )
        return _response.data


class AsyncUserStoresClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserStoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserStoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserStoresClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        member_access_level: typing.Optional[
            typing.Union[OrganizationAccessLevelEnum, typing.Sequence[OrganizationAccessLevelEnum]]
        ] = None,
        is_enabled: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserStoresResponseContent:
        """
        Retrieve the user stores for the associated Organization.

        Parameters
        ----------
        member_access_level : typing.Optional[typing.Union[OrganizationAccessLevelEnum, typing.Sequence[OrganizationAccessLevelEnum]]]
            When present, only connections whose Organization Member Access Level matches one of the provided values are returned. Accepted values are full, limited, readonly and none.

        is_enabled : typing.Optional[bool]
            Filter the returned list by enabled status. When `true`, only enabled items are returned; when `false`, only disabled items; when omitted, all items are returned.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserStoresResponseContent
            Retrieve user stores for an Organization.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.user_stores.list(
                member_access_level=["none"],
                is_enabled=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            member_access_level=member_access_level, is_enabled=is_enabled, request_options=request_options
        )
        return _response.data
