# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.org_member_id import OrgMemberId
from .raw_client import AsyncRawMembershipsClient, RawMembershipsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MembershipsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMembershipsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMembershipsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMembershipsClient
        """
        return self._raw_client

    def delete_memberships(
        self, *, members: typing.Sequence[OrgMemberId], request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove one member from this Organization. The underlying user account is not deleted.

        Parameters
        ----------
        members : typing.Sequence[OrgMemberId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.memberships.delete_memberships(
            members=["auth0|1234567890"],
        )
        """
        _response = self._raw_client.delete_memberships(members=members, request_options=request_options)
        return _response.data


class AsyncMembershipsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMembershipsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMembershipsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMembershipsClient
        """
        return self._raw_client

    async def delete_memberships(
        self, *, members: typing.Sequence[OrgMemberId], request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove one member from this Organization. The underlying user account is not deleted.

        Parameters
        ----------
        members : typing.Sequence[OrgMemberId]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.memberships.delete_memberships(
                members=["auth0|1234567890"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_memberships(members=members, request_options=request_options)
        return _response.data
