# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.create_idp_domain_response_content import CreateIdpDomainResponseContent
from ....types.idp_id import IdpId
from ....types.org_domain_name import OrgDomainName
from .raw_client import AsyncRawDomainsClient, RawDomainsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DomainsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDomainsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDomainsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDomainsClient
        """
        return self._raw_client

    def create(
        self, idp_id: IdpId, *, domain: OrgDomainName, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateIdpDomainResponseContent:
        """
        Associate a domain with an Identity Provider specified by ID for this Organization. The domain must be claimed and verified.

        Parameters
        ----------
        idp_id : IdpId

        domain : OrgDomainName

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdpDomainResponseContent
            Domain successfully associated with identity provider.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.domains.create(
            idp_id="idp_id",
            domain="my-domain.com",
        )
        """
        _response = self._raw_client.create(idp_id, domain=domain, request_options=request_options)
        return _response.data

    def delete(
        self, idp_id: IdpId, domain: OrgDomainName, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a domain specified by name from an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        domain : OrgDomainName

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.domains.delete(
            idp_id="idp_id",
            domain="domain",
        )
        """
        _response = self._raw_client.delete(idp_id, domain, request_options=request_options)
        return _response.data


class AsyncDomainsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDomainsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDomainsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDomainsClient
        """
        return self._raw_client

    async def create(
        self, idp_id: IdpId, *, domain: OrgDomainName, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateIdpDomainResponseContent:
        """
        Associate a domain with an Identity Provider specified by ID for this Organization. The domain must be claimed and verified.

        Parameters
        ----------
        idp_id : IdpId

        domain : OrgDomainName

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdpDomainResponseContent
            Domain successfully associated with identity provider.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.domains.create(
                idp_id="idp_id",
                domain="my-domain.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(idp_id, domain=domain, request_options=request_options)
        return _response.data

    async def delete(
        self, idp_id: IdpId, domain: OrgDomainName, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a domain specified by name from an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        domain : OrgDomainName

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.domains.delete(
                idp_id="idp_id",
                domain="domain",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(idp_id, domain, request_options=request_options)
        return _response.data
