# This file was auto-generated by Fern from our API Definition.

import typing

from .....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .....core.request_options import RequestOptions
from .....types.create_idp_provisioning_scim_token_response_content import CreateIdpProvisioningScimTokenResponseContent
from .....types.idp_id import IdpId
from .....types.idp_provisioning_scim_token_id import IdpProvisioningScimTokenId
from .....types.list_idp_provisioning_scim_tokens_response_content import ListIdpProvisioningScimTokensResponseContent
from .raw_client import AsyncRawScimTokensClient, RawScimTokensClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ScimTokensClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawScimTokensClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawScimTokensClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawScimTokensClient
        """
        return self._raw_client

    def list(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListIdpProvisioningScimTokensResponseContent:
        """
        Retrieve a list of [SCIM tokens](https://auth0.com/docs/authenticate/protocols/scim/configure-inbound-scim#scim-endpoints-and-tokens) for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIdpProvisioningScimTokensResponseContent
            List Provisioning SCIM tokens for an identity provider.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.scim_tokens.list(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.list(idp_id, request_options=request_options)
        return _response.data

    def create(
        self,
        idp_id: IdpId,
        *,
        token_lifetime: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateIdpProvisioningScimTokenResponseContent:
        """
        Create a new SCIM token for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        token_lifetime : typing.Optional[int]
            Lifetime of the token in seconds. Do not set for non-expiring tokens.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdpProvisioningScimTokenResponseContent
            Provisioning SCIM token successfully created.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.scim_tokens.create(
            idp_id="idp_id",
            token_lifetime=86400,
        )
        """
        _response = self._raw_client.create(idp_id, token_lifetime=token_lifetime, request_options=request_options)
        return _response.data

    def delete(
        self,
        idp_id: IdpId,
        idp_scim_token_id: IdpProvisioningScimTokenId,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Revoke a SCIM token specified by token ID for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        idp_scim_token_id : IdpProvisioningScimTokenId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.provisioning.scim_tokens.delete(
            idp_id="idp_id",
            idp_scim_token_id="idp_scim_token_id",
        )
        """
        _response = self._raw_client.delete(idp_id, idp_scim_token_id, request_options=request_options)
        return _response.data


class AsyncScimTokensClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawScimTokensClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawScimTokensClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawScimTokensClient
        """
        return self._raw_client

    async def list(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListIdpProvisioningScimTokensResponseContent:
        """
        Retrieve a list of [SCIM tokens](https://auth0.com/docs/authenticate/protocols/scim/configure-inbound-scim#scim-endpoints-and-tokens) for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIdpProvisioningScimTokensResponseContent
            List Provisioning SCIM tokens for an identity provider.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.scim_tokens.list(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(idp_id, request_options=request_options)
        return _response.data

    async def create(
        self,
        idp_id: IdpId,
        *,
        token_lifetime: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateIdpProvisioningScimTokenResponseContent:
        """
        Create a new SCIM token for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        token_lifetime : typing.Optional[int]
            Lifetime of the token in seconds. Do not set for non-expiring tokens.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdpProvisioningScimTokenResponseContent
            Provisioning SCIM token successfully created.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.scim_tokens.create(
                idp_id="idp_id",
                token_lifetime=86400,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            idp_id, token_lifetime=token_lifetime, request_options=request_options
        )
        return _response.data

    async def delete(
        self,
        idp_id: IdpId,
        idp_scim_token_id: IdpProvisioningScimTokenId,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Revoke a SCIM token specified by token ID for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        idp_scim_token_id : IdpProvisioningScimTokenId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.provisioning.scim_tokens.delete(
                idp_id="idp_id",
                idp_scim_token_id="idp_scim_token_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(idp_id, idp_scim_token_id, request_options=request_options)
        return _response.data
