# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from .....core.api_error import ApiError
from .....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .....core.http_response import AsyncHttpResponse, HttpResponse
from .....core.jsonable_encoder import jsonable_encoder
from .....core.pydantic_utilities import parse_obj_as
from .....core.request_options import RequestOptions
from .....errors.bad_request_error import BadRequestError
from .....errors.forbidden_error import ForbiddenError
from .....errors.not_found_error import NotFoundError
from .....errors.too_many_requests_error import TooManyRequestsError
from .....errors.unauthorized_error import UnauthorizedError
from .....types.create_idp_provisioning_scim_token_response_content import CreateIdpProvisioningScimTokenResponseContent
from .....types.error_response_content import ErrorResponseContent
from .....types.idp_id import IdpId
from .....types.idp_provisioning_scim_token_id import IdpProvisioningScimTokenId
from .....types.list_idp_provisioning_scim_tokens_response_content import ListIdpProvisioningScimTokensResponseContent

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawScimTokensClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListIdpProvisioningScimTokensResponseContent]:
        """
        List the Provisioning SCIM tokens for this identity provider.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListIdpProvisioningScimTokensResponseContent]
            List Provisioning SCIM tokens for an identity provider.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"identity-providers/{jsonable_encoder(idp_id)}/provisioning/scim-tokens",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListIdpProvisioningScimTokensResponseContent,
                    parse_obj_as(
                        type_=ListIdpProvisioningScimTokensResponseContent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        idp_id: IdpId,
        *,
        token_lifetime: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateIdpProvisioningScimTokenResponseContent]:
        """
        Create a Provisioning SCIM token for this identity provider.

        Parameters
        ----------
        idp_id : IdpId

        token_lifetime : typing.Optional[int]
            Lifetime of the token in seconds. Do not set for non-expiring tokens.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateIdpProvisioningScimTokenResponseContent]
            Provisioning SCIM token successfully created.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"identity-providers/{jsonable_encoder(idp_id)}/provisioning/scim-tokens",
            method="POST",
            json={
                "token_lifetime": token_lifetime,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateIdpProvisioningScimTokenResponseContent,
                    parse_obj_as(
                        type_=CreateIdpProvisioningScimTokenResponseContent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self,
        idp_id: IdpId,
        idp_scim_token_id: IdpProvisioningScimTokenId,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Delete a Provisioning SCIM configuration for an identity provider.

        Parameters
        ----------
        idp_id : IdpId

        idp_scim_token_id : IdpProvisioningScimTokenId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"identity-providers/{jsonable_encoder(idp_id)}/provisioning/scim-tokens/{jsonable_encoder(idp_scim_token_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawScimTokensClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListIdpProvisioningScimTokensResponseContent]:
        """
        List the Provisioning SCIM tokens for this identity provider.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListIdpProvisioningScimTokensResponseContent]
            List Provisioning SCIM tokens for an identity provider.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"identity-providers/{jsonable_encoder(idp_id)}/provisioning/scim-tokens",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListIdpProvisioningScimTokensResponseContent,
                    parse_obj_as(
                        type_=ListIdpProvisioningScimTokensResponseContent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        idp_id: IdpId,
        *,
        token_lifetime: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateIdpProvisioningScimTokenResponseContent]:
        """
        Create a Provisioning SCIM token for this identity provider.

        Parameters
        ----------
        idp_id : IdpId

        token_lifetime : typing.Optional[int]
            Lifetime of the token in seconds. Do not set for non-expiring tokens.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateIdpProvisioningScimTokenResponseContent]
            Provisioning SCIM token successfully created.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"identity-providers/{jsonable_encoder(idp_id)}/provisioning/scim-tokens",
            method="POST",
            json={
                "token_lifetime": token_lifetime,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateIdpProvisioningScimTokenResponseContent,
                    parse_obj_as(
                        type_=CreateIdpProvisioningScimTokenResponseContent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self,
        idp_id: IdpId,
        idp_scim_token_id: IdpProvisioningScimTokenId,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Delete a Provisioning SCIM configuration for an identity provider.

        Parameters
        ----------
        idp_id : IdpId

        idp_scim_token_id : IdpProvisioningScimTokenId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"identity-providers/{jsonable_encoder(idp_id)}/provisioning/scim-tokens/{jsonable_encoder(idp_scim_token_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponseContent,
                        parse_obj_as(
                            type_=ErrorResponseContent,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
