# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .automatic import Automatic
    from .bad_request_error_body import BadRequestErrorBody
    from .base_user_attribute_map_item import BaseUserAttributeMapItem
    from .create_id_p_provisioning_config_response_content import CreateIdPProvisioningConfigResponseContent
    from .create_identity_provider_request_content import CreateIdentityProviderRequestContent
    from .create_identity_provider_response_content import CreateIdentityProviderResponseContent
    from .create_idp_domain_response_content import CreateIdpDomainResponseContent
    from .create_idp_provisioning_scim_token_response_content import CreateIdpProvisioningScimTokenResponseContent
    from .create_member_invitation_response_content import CreateMemberInvitationResponseContent
    from .create_organization_domain_response_content import CreateOrganizationDomainResponseContent
    from .domain_idp import DomainIdp
    from .domain_verification_enum import DomainVerificationEnum
    from .error_response_content import ErrorResponseContent
    from .fed_metadata_xml import FedMetadataXml
    from .get_configuration_response_content import GetConfigurationResponseContent
    from .get_id_p_provisioning_config_response_content import GetIdPProvisioningConfigResponseContent
    from .get_identity_provider_response_content import GetIdentityProviderResponseContent
    from .get_idp_configuration_response_content import GetIdpConfigurationResponseContent
    from .get_member_invitation_response_content import GetMemberInvitationResponseContent
    from .get_organization_details_response_content import GetOrganizationDetailsResponseContent
    from .get_organization_domain_response_content import GetOrganizationDomainResponseContent
    from .get_organization_member_response_content import GetOrganizationMemberResponseContent
    from .identity_provider_config_adfs import IdentityProviderConfigAdfs
    from .identity_provider_config_google_apps import IdentityProviderConfigGoogleApps
    from .identity_provider_config_oidc import IdentityProviderConfigOidc
    from .identity_provider_config_okta import IdentityProviderConfigOkta
    from .identity_provider_config_ping_federate import IdentityProviderConfigPingFederate
    from .identity_provider_config_samlp import IdentityProviderConfigSamlp
    from .identity_provider_config_waad import IdentityProviderConfigWaad
    from .identity_providers_config import IdentityProvidersConfig
    from .identity_providers_config_domain_alias import IdentityProvidersConfigDomainAlias
    from .identity_providers_config_enabled_features_enum import IdentityProvidersConfigEnabledFeaturesEnum
    from .identity_providers_config_organization import IdentityProvidersConfigOrganization
    from .identity_providers_config_provisioning_methods_enum import IdentityProvidersConfigProvisioningMethodsEnum
    from .identity_providers_config_strategy_base import IdentityProvidersConfigStrategyBase
    from .identity_providers_config_strategy_override import IdentityProvidersConfigStrategyOverride
    from .idp_adfs_options_request import IdpAdfsOptionsRequest
    from .idp_adfs_options_request_adfs_server import IdpAdfsOptionsRequestAdfsServer
    from .idp_adfs_options_response import IdpAdfsOptionsResponse
    from .idp_adfs_options_response_adfs_server import IdpAdfsOptionsResponseAdfsServer
    from .idp_adfs_request import IdpAdfsRequest
    from .idp_adfs_request_strategy import IdpAdfsRequestStrategy
    from .idp_adfs_response import IdpAdfsResponse
    from .idp_adfs_response_strategy import IdpAdfsResponseStrategy
    from .idp_adfs_update_request import IdpAdfsUpdateRequest
    from .idp_base_request import IdpBaseRequest
    from .idp_base_response import IdpBaseResponse
    from .idp_connection_deletion_behavior_enum import IdpConnectionDeletionBehaviorEnum
    from .idp_google_apps_options_request import IdpGoogleAppsOptionsRequest
    from .idp_google_apps_options_response import IdpGoogleAppsOptionsResponse
    from .idp_google_apps_request import IdpGoogleAppsRequest
    from .idp_google_apps_request_strategy import IdpGoogleAppsRequestStrategy
    from .idp_google_apps_response import IdpGoogleAppsResponse
    from .idp_google_apps_response_strategy import IdpGoogleAppsResponseStrategy
    from .idp_google_apps_update_request import IdpGoogleAppsUpdateRequest
    from .idp_id import IdpId
    from .idp_known_request import IdpKnownRequest
    from .idp_known_response import IdpKnownResponse
    from .idp_oidc_options_request import IdpOidcOptionsRequest
    from .idp_oidc_options_response import IdpOidcOptionsResponse
    from .idp_oidc_options_type_enum import IdpOidcOptionsTypeEnum
    from .idp_oidc_request import IdpOidcRequest
    from .idp_oidc_request_strategy import IdpOidcRequestStrategy
    from .idp_oidc_response import IdpOidcResponse
    from .idp_oidc_response_strategy import IdpOidcResponseStrategy
    from .idp_oidc_update_request import IdpOidcUpdateRequest
    from .idp_okta_options_request import IdpOktaOptionsRequest
    from .idp_okta_options_response import IdpOktaOptionsResponse
    from .idp_okta_request import IdpOktaRequest
    from .idp_okta_request_strategy import IdpOktaRequestStrategy
    from .idp_okta_response import IdpOktaResponse
    from .idp_okta_response_strategy import IdpOktaResponseStrategy
    from .idp_okta_update_request import IdpOktaUpdateRequest
    from .idp_options_idp_initiated import IdpOptionsIdpInitiated
    from .idp_ping_federate_options_request import IdpPingFederateOptionsRequest
    from .idp_ping_federate_options_response import IdpPingFederateOptionsResponse
    from .idp_ping_federate_request import IdpPingFederateRequest
    from .idp_ping_federate_request_strategy import IdpPingFederateRequestStrategy
    from .idp_ping_federate_response import IdpPingFederateResponse
    from .idp_ping_federate_response_strategy import IdpPingFederateResponseStrategy
    from .idp_ping_federate_update_request import IdpPingFederateUpdateRequest
    from .idp_protocol_binding_type_enum import IdpProtocolBindingTypeEnum
    from .idp_provisioning_config import IdpProvisioningConfig
    from .idp_provisioning_method_enum import IdpProvisioningMethodEnum
    from .idp_provisioning_scim_token_id import IdpProvisioningScimTokenId
    from .idp_provisioning_user_attribute_map_item import IdpProvisioningUserAttributeMapItem
    from .idp_samlp_options_request import IdpSamlpOptionsRequest
    from .idp_samlp_options_response import IdpSamlpOptionsResponse
    from .idp_samlp_request import IdpSamlpRequest
    from .idp_samlp_request_strategy import IdpSamlpRequestStrategy
    from .idp_samlp_response import IdpSamlpResponse
    from .idp_samlp_response_strategy import IdpSamlpResponseStrategy
    from .idp_samlp_update_request import IdpSamlpUpdateRequest
    from .idp_scim_token_base import IdpScimTokenBase
    from .idp_scim_token_create import IdpScimTokenCreate
    from .idp_scim_token_read import IdpScimTokenRead
    from .idp_sign_alg_digest_type_enum import IdpSignAlgDigestTypeEnum
    from .idp_sign_alg_type_enum import IdpSignAlgTypeEnum
    from .idp_strategy_enum import IdpStrategyEnum
    from .idp_update_base import IdpUpdateBase
    from .idp_update_known_request import IdpUpdateKnownRequest
    from .idp_update_known_response import IdpUpdateKnownResponse
    from .idp_user_attribute_map_item import IdpUserAttributeMapItem
    from .idp_waad_options_request import IdpWaadOptionsRequest
    from .idp_waad_options_response import IdpWaadOptionsResponse
    from .idp_waad_request import IdpWaadRequest
    from .idp_waad_request_strategy import IdpWaadRequestStrategy
    from .idp_waad_response import IdpWaadResponse
    from .idp_waad_response_strategy import IdpWaadResponseStrategy
    from .idp_waad_update_request import IdpWaadUpdateRequest
    from .invitation_id import InvitationId
    from .list_domain_identity_providers_response_content import ListDomainIdentityProvidersResponseContent
    from .list_identity_providers_response_content import ListIdentityProvidersResponseContent
    from .list_idp_provisioning_scim_tokens_response_content import ListIdpProvisioningScimTokensResponseContent
    from .list_organization_domains_response_content import ListOrganizationDomainsResponseContent
    from .manual import Manual
    from .member_invitation import MemberInvitation
    from .member_invitation_invitee import MemberInvitationInvitee
    from .member_invitation_inviter import MemberInvitationInviter
    from .oauth_scope import OauthScope
    from .org_branding import OrgBranding
    from .org_branding_colors import OrgBrandingColors
    from .org_details import OrgDetails
    from .org_domain import OrgDomain
    from .org_domain_id import OrgDomainId
    from .org_domain_name import OrgDomainName
    from .org_domain_status_enum import OrgDomainStatusEnum
    from .org_id import OrgId
    from .org_member import OrgMember
    from .org_member_id import OrgMemberId
    from .org_member_role import OrgMemberRole
    from .org_member_role_id import OrgMemberRoleId
    from .organization_access_level_enum import OrganizationAccessLevelEnum
    from .start_organization_domain_verification_response_content import (
        StartOrganizationDomainVerificationResponseContent,
    )
    from .update_identity_provider_request_content import UpdateIdentityProviderRequestContent
    from .update_identity_provider_response_content import UpdateIdentityProviderResponseContent
    from .update_organization_details_request_content import UpdateOrganizationDetailsRequestContent
    from .update_organization_details_response_content import UpdateOrganizationDetailsResponseContent
    from .user_attributes import UserAttributes
    from .validation_error_detail import ValidationErrorDetail
    from .validation_error_response_content import ValidationErrorResponseContent
_dynamic_imports: typing.Dict[str, str] = {
    "Automatic": ".automatic",
    "BadRequestErrorBody": ".bad_request_error_body",
    "BaseUserAttributeMapItem": ".base_user_attribute_map_item",
    "CreateIdPProvisioningConfigResponseContent": ".create_id_p_provisioning_config_response_content",
    "CreateIdentityProviderRequestContent": ".create_identity_provider_request_content",
    "CreateIdentityProviderResponseContent": ".create_identity_provider_response_content",
    "CreateIdpDomainResponseContent": ".create_idp_domain_response_content",
    "CreateIdpProvisioningScimTokenResponseContent": ".create_idp_provisioning_scim_token_response_content",
    "CreateMemberInvitationResponseContent": ".create_member_invitation_response_content",
    "CreateOrganizationDomainResponseContent": ".create_organization_domain_response_content",
    "DomainIdp": ".domain_idp",
    "DomainVerificationEnum": ".domain_verification_enum",
    "ErrorResponseContent": ".error_response_content",
    "FedMetadataXml": ".fed_metadata_xml",
    "GetConfigurationResponseContent": ".get_configuration_response_content",
    "GetIdPProvisioningConfigResponseContent": ".get_id_p_provisioning_config_response_content",
    "GetIdentityProviderResponseContent": ".get_identity_provider_response_content",
    "GetIdpConfigurationResponseContent": ".get_idp_configuration_response_content",
    "GetMemberInvitationResponseContent": ".get_member_invitation_response_content",
    "GetOrganizationDetailsResponseContent": ".get_organization_details_response_content",
    "GetOrganizationDomainResponseContent": ".get_organization_domain_response_content",
    "GetOrganizationMemberResponseContent": ".get_organization_member_response_content",
    "IdentityProviderConfigAdfs": ".identity_provider_config_adfs",
    "IdentityProviderConfigGoogleApps": ".identity_provider_config_google_apps",
    "IdentityProviderConfigOidc": ".identity_provider_config_oidc",
    "IdentityProviderConfigOkta": ".identity_provider_config_okta",
    "IdentityProviderConfigPingFederate": ".identity_provider_config_ping_federate",
    "IdentityProviderConfigSamlp": ".identity_provider_config_samlp",
    "IdentityProviderConfigWaad": ".identity_provider_config_waad",
    "IdentityProvidersConfig": ".identity_providers_config",
    "IdentityProvidersConfigDomainAlias": ".identity_providers_config_domain_alias",
    "IdentityProvidersConfigEnabledFeaturesEnum": ".identity_providers_config_enabled_features_enum",
    "IdentityProvidersConfigOrganization": ".identity_providers_config_organization",
    "IdentityProvidersConfigProvisioningMethodsEnum": ".identity_providers_config_provisioning_methods_enum",
    "IdentityProvidersConfigStrategyBase": ".identity_providers_config_strategy_base",
    "IdentityProvidersConfigStrategyOverride": ".identity_providers_config_strategy_override",
    "IdpAdfsOptionsRequest": ".idp_adfs_options_request",
    "IdpAdfsOptionsRequestAdfsServer": ".idp_adfs_options_request_adfs_server",
    "IdpAdfsOptionsResponse": ".idp_adfs_options_response",
    "IdpAdfsOptionsResponseAdfsServer": ".idp_adfs_options_response_adfs_server",
    "IdpAdfsRequest": ".idp_adfs_request",
    "IdpAdfsRequestStrategy": ".idp_adfs_request_strategy",
    "IdpAdfsResponse": ".idp_adfs_response",
    "IdpAdfsResponseStrategy": ".idp_adfs_response_strategy",
    "IdpAdfsUpdateRequest": ".idp_adfs_update_request",
    "IdpBaseRequest": ".idp_base_request",
    "IdpBaseResponse": ".idp_base_response",
    "IdpConnectionDeletionBehaviorEnum": ".idp_connection_deletion_behavior_enum",
    "IdpGoogleAppsOptionsRequest": ".idp_google_apps_options_request",
    "IdpGoogleAppsOptionsResponse": ".idp_google_apps_options_response",
    "IdpGoogleAppsRequest": ".idp_google_apps_request",
    "IdpGoogleAppsRequestStrategy": ".idp_google_apps_request_strategy",
    "IdpGoogleAppsResponse": ".idp_google_apps_response",
    "IdpGoogleAppsResponseStrategy": ".idp_google_apps_response_strategy",
    "IdpGoogleAppsUpdateRequest": ".idp_google_apps_update_request",
    "IdpId": ".idp_id",
    "IdpKnownRequest": ".idp_known_request",
    "IdpKnownResponse": ".idp_known_response",
    "IdpOidcOptionsRequest": ".idp_oidc_options_request",
    "IdpOidcOptionsResponse": ".idp_oidc_options_response",
    "IdpOidcOptionsTypeEnum": ".idp_oidc_options_type_enum",
    "IdpOidcRequest": ".idp_oidc_request",
    "IdpOidcRequestStrategy": ".idp_oidc_request_strategy",
    "IdpOidcResponse": ".idp_oidc_response",
    "IdpOidcResponseStrategy": ".idp_oidc_response_strategy",
    "IdpOidcUpdateRequest": ".idp_oidc_update_request",
    "IdpOktaOptionsRequest": ".idp_okta_options_request",
    "IdpOktaOptionsResponse": ".idp_okta_options_response",
    "IdpOktaRequest": ".idp_okta_request",
    "IdpOktaRequestStrategy": ".idp_okta_request_strategy",
    "IdpOktaResponse": ".idp_okta_response",
    "IdpOktaResponseStrategy": ".idp_okta_response_strategy",
    "IdpOktaUpdateRequest": ".idp_okta_update_request",
    "IdpOptionsIdpInitiated": ".idp_options_idp_initiated",
    "IdpPingFederateOptionsRequest": ".idp_ping_federate_options_request",
    "IdpPingFederateOptionsResponse": ".idp_ping_federate_options_response",
    "IdpPingFederateRequest": ".idp_ping_federate_request",
    "IdpPingFederateRequestStrategy": ".idp_ping_federate_request_strategy",
    "IdpPingFederateResponse": ".idp_ping_federate_response",
    "IdpPingFederateResponseStrategy": ".idp_ping_federate_response_strategy",
    "IdpPingFederateUpdateRequest": ".idp_ping_federate_update_request",
    "IdpProtocolBindingTypeEnum": ".idp_protocol_binding_type_enum",
    "IdpProvisioningConfig": ".idp_provisioning_config",
    "IdpProvisioningMethodEnum": ".idp_provisioning_method_enum",
    "IdpProvisioningScimTokenId": ".idp_provisioning_scim_token_id",
    "IdpProvisioningUserAttributeMapItem": ".idp_provisioning_user_attribute_map_item",
    "IdpSamlpOptionsRequest": ".idp_samlp_options_request",
    "IdpSamlpOptionsResponse": ".idp_samlp_options_response",
    "IdpSamlpRequest": ".idp_samlp_request",
    "IdpSamlpRequestStrategy": ".idp_samlp_request_strategy",
    "IdpSamlpResponse": ".idp_samlp_response",
    "IdpSamlpResponseStrategy": ".idp_samlp_response_strategy",
    "IdpSamlpUpdateRequest": ".idp_samlp_update_request",
    "IdpScimTokenBase": ".idp_scim_token_base",
    "IdpScimTokenCreate": ".idp_scim_token_create",
    "IdpScimTokenRead": ".idp_scim_token_read",
    "IdpSignAlgDigestTypeEnum": ".idp_sign_alg_digest_type_enum",
    "IdpSignAlgTypeEnum": ".idp_sign_alg_type_enum",
    "IdpStrategyEnum": ".idp_strategy_enum",
    "IdpUpdateBase": ".idp_update_base",
    "IdpUpdateKnownRequest": ".idp_update_known_request",
    "IdpUpdateKnownResponse": ".idp_update_known_response",
    "IdpUserAttributeMapItem": ".idp_user_attribute_map_item",
    "IdpWaadOptionsRequest": ".idp_waad_options_request",
    "IdpWaadOptionsResponse": ".idp_waad_options_response",
    "IdpWaadRequest": ".idp_waad_request",
    "IdpWaadRequestStrategy": ".idp_waad_request_strategy",
    "IdpWaadResponse": ".idp_waad_response",
    "IdpWaadResponseStrategy": ".idp_waad_response_strategy",
    "IdpWaadUpdateRequest": ".idp_waad_update_request",
    "InvitationId": ".invitation_id",
    "ListDomainIdentityProvidersResponseContent": ".list_domain_identity_providers_response_content",
    "ListIdentityProvidersResponseContent": ".list_identity_providers_response_content",
    "ListIdpProvisioningScimTokensResponseContent": ".list_idp_provisioning_scim_tokens_response_content",
    "ListOrganizationDomainsResponseContent": ".list_organization_domains_response_content",
    "Manual": ".manual",
    "MemberInvitation": ".member_invitation",
    "MemberInvitationInvitee": ".member_invitation_invitee",
    "MemberInvitationInviter": ".member_invitation_inviter",
    "OauthScope": ".oauth_scope",
    "OrgBranding": ".org_branding",
    "OrgBrandingColors": ".org_branding_colors",
    "OrgDetails": ".org_details",
    "OrgDomain": ".org_domain",
    "OrgDomainId": ".org_domain_id",
    "OrgDomainName": ".org_domain_name",
    "OrgDomainStatusEnum": ".org_domain_status_enum",
    "OrgId": ".org_id",
    "OrgMember": ".org_member",
    "OrgMemberId": ".org_member_id",
    "OrgMemberRole": ".org_member_role",
    "OrgMemberRoleId": ".org_member_role_id",
    "OrganizationAccessLevelEnum": ".organization_access_level_enum",
    "StartOrganizationDomainVerificationResponseContent": ".start_organization_domain_verification_response_content",
    "UpdateIdentityProviderRequestContent": ".update_identity_provider_request_content",
    "UpdateIdentityProviderResponseContent": ".update_identity_provider_response_content",
    "UpdateOrganizationDetailsRequestContent": ".update_organization_details_request_content",
    "UpdateOrganizationDetailsResponseContent": ".update_organization_details_response_content",
    "UserAttributes": ".user_attributes",
    "ValidationErrorDetail": ".validation_error_detail",
    "ValidationErrorResponseContent": ".validation_error_response_content",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Automatic",
    "BadRequestErrorBody",
    "BaseUserAttributeMapItem",
    "CreateIdPProvisioningConfigResponseContent",
    "CreateIdentityProviderRequestContent",
    "CreateIdentityProviderResponseContent",
    "CreateIdpDomainResponseContent",
    "CreateIdpProvisioningScimTokenResponseContent",
    "CreateMemberInvitationResponseContent",
    "CreateOrganizationDomainResponseContent",
    "DomainIdp",
    "DomainVerificationEnum",
    "ErrorResponseContent",
    "FedMetadataXml",
    "GetConfigurationResponseContent",
    "GetIdPProvisioningConfigResponseContent",
    "GetIdentityProviderResponseContent",
    "GetIdpConfigurationResponseContent",
    "GetMemberInvitationResponseContent",
    "GetOrganizationDetailsResponseContent",
    "GetOrganizationDomainResponseContent",
    "GetOrganizationMemberResponseContent",
    "IdentityProviderConfigAdfs",
    "IdentityProviderConfigGoogleApps",
    "IdentityProviderConfigOidc",
    "IdentityProviderConfigOkta",
    "IdentityProviderConfigPingFederate",
    "IdentityProviderConfigSamlp",
    "IdentityProviderConfigWaad",
    "IdentityProvidersConfig",
    "IdentityProvidersConfigDomainAlias",
    "IdentityProvidersConfigEnabledFeaturesEnum",
    "IdentityProvidersConfigOrganization",
    "IdentityProvidersConfigProvisioningMethodsEnum",
    "IdentityProvidersConfigStrategyBase",
    "IdentityProvidersConfigStrategyOverride",
    "IdpAdfsOptionsRequest",
    "IdpAdfsOptionsRequestAdfsServer",
    "IdpAdfsOptionsResponse",
    "IdpAdfsOptionsResponseAdfsServer",
    "IdpAdfsRequest",
    "IdpAdfsRequestStrategy",
    "IdpAdfsResponse",
    "IdpAdfsResponseStrategy",
    "IdpAdfsUpdateRequest",
    "IdpBaseRequest",
    "IdpBaseResponse",
    "IdpConnectionDeletionBehaviorEnum",
    "IdpGoogleAppsOptionsRequest",
    "IdpGoogleAppsOptionsResponse",
    "IdpGoogleAppsRequest",
    "IdpGoogleAppsRequestStrategy",
    "IdpGoogleAppsResponse",
    "IdpGoogleAppsResponseStrategy",
    "IdpGoogleAppsUpdateRequest",
    "IdpId",
    "IdpKnownRequest",
    "IdpKnownResponse",
    "IdpOidcOptionsRequest",
    "IdpOidcOptionsResponse",
    "IdpOidcOptionsTypeEnum",
    "IdpOidcRequest",
    "IdpOidcRequestStrategy",
    "IdpOidcResponse",
    "IdpOidcResponseStrategy",
    "IdpOidcUpdateRequest",
    "IdpOktaOptionsRequest",
    "IdpOktaOptionsResponse",
    "IdpOktaRequest",
    "IdpOktaRequestStrategy",
    "IdpOktaResponse",
    "IdpOktaResponseStrategy",
    "IdpOktaUpdateRequest",
    "IdpOptionsIdpInitiated",
    "IdpPingFederateOptionsRequest",
    "IdpPingFederateOptionsResponse",
    "IdpPingFederateRequest",
    "IdpPingFederateRequestStrategy",
    "IdpPingFederateResponse",
    "IdpPingFederateResponseStrategy",
    "IdpPingFederateUpdateRequest",
    "IdpProtocolBindingTypeEnum",
    "IdpProvisioningConfig",
    "IdpProvisioningMethodEnum",
    "IdpProvisioningScimTokenId",
    "IdpProvisioningUserAttributeMapItem",
    "IdpSamlpOptionsRequest",
    "IdpSamlpOptionsResponse",
    "IdpSamlpRequest",
    "IdpSamlpRequestStrategy",
    "IdpSamlpResponse",
    "IdpSamlpResponseStrategy",
    "IdpSamlpUpdateRequest",
    "IdpScimTokenBase",
    "IdpScimTokenCreate",
    "IdpScimTokenRead",
    "IdpSignAlgDigestTypeEnum",
    "IdpSignAlgTypeEnum",
    "IdpStrategyEnum",
    "IdpUpdateBase",
    "IdpUpdateKnownRequest",
    "IdpUpdateKnownResponse",
    "IdpUserAttributeMapItem",
    "IdpWaadOptionsRequest",
    "IdpWaadOptionsResponse",
    "IdpWaadRequest",
    "IdpWaadRequestStrategy",
    "IdpWaadResponse",
    "IdpWaadResponseStrategy",
    "IdpWaadUpdateRequest",
    "InvitationId",
    "ListDomainIdentityProvidersResponseContent",
    "ListIdentityProvidersResponseContent",
    "ListIdpProvisioningScimTokensResponseContent",
    "ListOrganizationDomainsResponseContent",
    "Manual",
    "MemberInvitation",
    "MemberInvitationInvitee",
    "MemberInvitationInviter",
    "OauthScope",
    "OrgBranding",
    "OrgBrandingColors",
    "OrgDetails",
    "OrgDomain",
    "OrgDomainId",
    "OrgDomainName",
    "OrgDomainStatusEnum",
    "OrgId",
    "OrgMember",
    "OrgMemberId",
    "OrgMemberRole",
    "OrgMemberRoleId",
    "OrganizationAccessLevelEnum",
    "StartOrganizationDomainVerificationResponseContent",
    "UpdateIdentityProviderRequestContent",
    "UpdateIdentityProviderResponseContent",
    "UpdateOrganizationDetailsRequestContent",
    "UpdateOrganizationDetailsResponseContent",
    "UserAttributes",
    "ValidationErrorDetail",
    "ValidationErrorResponseContent",
]
