# This file was auto-generated by Fern from our API Definition.

import typing

from .error_response_content import ErrorResponseContent
from .validation_error_response_content import ValidationErrorResponseContent

BadRequestErrorBody = typing.Union[ErrorResponseContent, ValidationErrorResponseContent]
