# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BaseUserAttributeMapItem(UniversalBaseModel):
    user_attribute: str = pydantic.Field()
    """
    The name of the user attribute.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The description of the user attribute.
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    The label of the user attribute.
    """

    is_required: bool = pydantic.Field()
    """
    Indicates if the attribute is required.
    """

    is_extra: bool = pydantic.Field()
    """
    Indicates whether this attribute is not part of the admin defined schema but is provided by the source. The property will be removed when a refresh operation is performed.
    """

    is_missing: bool = pydantic.Field()
    """
    Indicates whether this attribute is expected but not provided by the admin defined schema. The property will   be added when a refresh operation is performed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
