# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cross_app_access_resource_app_status_enum import CrossAppAccessResourceAppStatusEnum


class CrossAppAccessResourceApp(UniversalBaseModel):
    """
    Cross-app access resource application configuration.
    """

    status: CrossAppAccessResourceAppStatusEnum = pydantic.Field()
    """
    The status of the cross-app access resource application role. To enable the cross-app access resource application role, OIDC issuer domain must be a verified domain for the organization.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
