# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cross_app_access_resource_app_status_config_enum import CrossAppAccessResourceAppStatusConfigEnum


class CrossAppAccessResourceAppStatusConfig(UniversalBaseModel):
    default_value: CrossAppAccessResourceAppStatusConfigEnum = pydantic.Field()
    """
    The value applied to `cross_app_access_resource_app.status` when an identity provider is created and no other value is specified.
    """

    allowed_values: typing.Optional[typing.List[CrossAppAccessResourceAppStatusConfigEnum]] = pydantic.Field(
        default=None
    )
    """
    A list of values, other than `default_value`, that may be set for `cross_app_access_resource_app.status` when creating or updating an identity provider. If omitted, only `default_value` is permitted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
