# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_id import IdpId


class DomainIdp(UniversalBaseModel):
    id: typing.Optional[IdpId] = None
    name: str = pydantic.Field()
    """
    The name of the identity provider
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identity provider name used on the login screen.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
