# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ErrorResponseContent(UniversalBaseModel):
    type: str = pydantic.Field()
    """
    A URI that describes the error.
    """

    status: int = pydantic.Field()
    """
    The HTTP status code result of the request.
    """

    title: str = pydantic.Field()
    """
    A brief description of the error.
    """

    detail: str = pydantic.Field()
    """
    A detailed description of the error.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
