# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_connection_deletion_behavior_enum import IdpConnectionDeletionBehaviorEnum
from .idp_strategy_enum import IdpStrategyEnum


class GetConfigurationResponseContent(UniversalBaseModel):
    allowed_strategies: typing.Optional[typing.List[IdpStrategyEnum]] = pydantic.Field(default=None)
    """
    Array of supported strategies
    """

    connection_deletion_behavior: typing.Optional[IdpConnectionDeletionBehaviorEnum] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
