# This file was auto-generated by Fern from our API Definition.

import typing

IdentityProvidersConfigProvisioningConfigurationOnLogin = typing.Union[
    typing.Literal["never_on_login", "on_first_login", "on_each_login"], typing.Any
]
