# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .identity_providers_config_provisioning_configuration_scim_tokens import (
    IdentityProvidersConfigProvisioningConfigurationScimTokens,
)


class IdentityProvidersConfigProvisioningConfigurationScim(UniversalBaseModel):
    """
    Provisioning configuration for SCIM
    """

    tokens: IdentityProvidersConfigProvisioningConfigurationScimTokens

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
