# This file was auto-generated by Fern from our API Definition.

import typing

from .identity_providers_config_provisioning_configuration_scim_tokens_scopes_enum import (
    IdentityProvidersConfigProvisioningConfigurationScimTokensScopesEnum,
)

IdentityProvidersConfigProvisioningConfigurationScimTokensScopes = typing.List[
    IdentityProvidersConfigProvisioningConfigurationScimTokensScopesEnum
]
