# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .identity_provider_config_adfs import IdentityProviderConfigAdfs
from .identity_provider_config_google_apps import IdentityProviderConfigGoogleApps
from .identity_provider_config_oidc import IdentityProviderConfigOidc
from .identity_provider_config_okta import IdentityProviderConfigOkta
from .identity_provider_config_ping_federate import IdentityProviderConfigPingFederate
from .identity_provider_config_samlp import IdentityProviderConfigSamlp
from .identity_provider_config_waad import IdentityProviderConfigWaad


class IdentityProvidersConfigStrategyOverride(UniversalBaseModel):
    """
    Strategy-specific overrides for identity providers
    """

    adfs: typing.Optional[IdentityProviderConfigAdfs] = None
    googleapps: typing.Optional[IdentityProviderConfigGoogleApps] = None
    oidc: typing.Optional[IdentityProviderConfigOidc] = None
    okta: typing.Optional[IdentityProviderConfigOkta] = None
    pingfederate: typing.Optional[IdentityProviderConfigPingFederate] = None
    samlp: typing.Optional[IdentityProviderConfigSamlp] = None
    waad: typing.Optional[IdentityProviderConfigWaad] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
