# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .identity_providers_config_enabled_features_enum import IdentityProvidersConfigEnabledFeaturesEnum
from .identity_providers_config_provisioning_methods_enum import IdentityProvidersConfigProvisioningMethodsEnum


class IdentityProvidersConfigStrategyBase(UniversalBaseModel):
    """
    Identity providers strategy configs
    """

    enabled_features: typing.List[IdentityProvidersConfigEnabledFeaturesEnum] = pydantic.Field()
    """
    Enabled features for a connections profile strategy override.
    """

    provisioning_methods: typing.List[IdentityProvidersConfigProvisioningMethodsEnum]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
