# This file was auto-generated by Fern from our API Definition.

from .identity_providers_config_strategy_base import IdentityProvidersConfigStrategyBase

IdentityProviderConfigOkta = IdentityProvidersConfigStrategyBase
