# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .identity_providers_config_provisioning_configuration_scim_tokens_scopes import (
    IdentityProvidersConfigProvisioningConfigurationScimTokensScopes,
)


class IdentityProvidersConfigProvisioningConfigurationScimTokens(UniversalBaseModel):
    scopes: typing.Optional[IdentityProvidersConfigProvisioningConfigurationScimTokensScopes] = None
    default_expiry: typing.Optional[int] = None
    max_allowed_expiry: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
