# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IdpGoogleAppsOptionsRequest(UniversalBaseModel):
    domain: str = pydantic.Field()
    """
    Google Workspace domain name for your organization.
    """

    client_id: str = pydantic.Field()
    """
    Unique identifier for your registered Google application.
    """

    client_secret: str = pydantic.Field()
    """
    String used to gain access to your registered Google application
    """

    icon_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A URL pointing to an image file that represents your client application.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
