# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IdpOptionsIdpInitiated(UniversalBaseModel):
    """
    An object containing configuration details for Identity Provider (IdP) initiated single sign-on flows
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    A flag indicating whether IdP-initiated SSO is enabled for this connection
    """

    client_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The client ID of your default application for which the IdP-initiated flow is being configured
    """

    client_protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the protocol used to connect your selected default application
    """

    client_authorizequery: typing.Optional[str] = pydantic.Field(default=None)
    """
    This field represents a template for constructing the authorization query string when initiating an IdP-initiated flow to a specific client
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
