# This file was auto-generated by Fern from our API Definition.

import typing

from .idp_adfs_update_request import IdpAdfsUpdateRequest
from .idp_google_apps_update_request import IdpGoogleAppsUpdateRequest
from .idp_oidc_update_request import IdpOidcUpdateRequest
from .idp_okta_update_request import IdpOktaUpdateRequest
from .idp_ping_federate_update_request import IdpPingFederateUpdateRequest
from .idp_samlp_update_request import IdpSamlpUpdateRequest
from .idp_waad_update_request import IdpWaadUpdateRequest

IdpUpdateKnownRequest = typing.Union[
    IdpAdfsUpdateRequest,
    IdpGoogleAppsUpdateRequest,
    IdpOidcUpdateRequest,
    IdpOktaUpdateRequest,
    IdpPingFederateUpdateRequest,
    IdpSamlpUpdateRequest,
    IdpWaadUpdateRequest,
]
