# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_id import IdpId
from .idp_provisioning_method_enum import IdpProvisioningMethodEnum
from .idp_provisioning_user_attribute_map_item import IdpProvisioningUserAttributeMapItem
from .idp_strategy_enum import IdpStrategyEnum


class IdpProvisioningConfig(UniversalBaseModel):
    identity_provider_id: typing.Optional[IdpId] = None
    identity_provider_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the identity provider
    """

    strategy: IdpStrategyEnum
    method: IdpProvisioningMethodEnum
    attributes: typing.List[IdpProvisioningUserAttributeMapItem]
    user_id_attribute: str = pydantic.Field()
    """
    The ID of the user
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
