# This file was auto-generated by Fern from our API Definition.

import typing

IdpStrategyEnum = typing.Union[
    typing.Literal["adfs", "google-apps", "oidc", "okta", "pingfederate", "samlp", "waad"], typing.Any
]
