# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_strategy_enum import IdpStrategyEnum


class IdpBaseRequest(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    The name of the identity provider
    """

    strategy: IdpStrategyEnum
    domains: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of domains for Home Realm Discovery (HRD)
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identity provider name used on the login screen.
    """

    show_as_button: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD).
    """

    assign_membership_on_login: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the user will be made a member of the organization upon login.
    """

    is_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True if the identity provider is enabled for the organization.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
