# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .idp_options_idp_initiated import IdpOptionsIdpInitiated
from .idp_sign_alg_digest_type_enum import IdpSignAlgDigestTypeEnum
from .idp_sign_alg_type_enum import IdpSignAlgTypeEnum


class IdpPingFederateOptionsResponse(UniversalBaseModel):
    signature_algorithm: typing_extensions.Annotated[
        typing.Optional[IdpSignAlgTypeEnum],
        FieldMetadata(alias="signatureAlgorithm"),
        pydantic.Field(alias="signatureAlgorithm"),
    ] = None
    digest_algorithm: typing_extensions.Annotated[
        typing.Optional[IdpSignAlgDigestTypeEnum],
        FieldMetadata(alias="digestAlgorithm"),
        pydantic.Field(alias="digestAlgorithm"),
    ] = None
    sign_saml_request: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="signSAMLRequest"),
        pydantic.Field(
            alias="signSAMLRequest",
            description="Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties",
        ),
    ] = None
    ping_federate_base_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="pingFederateBaseUrl"),
        pydantic.Field(
            alias="pingFederateBaseUrl",
            description="URL provided by PingFederate which returns information used for creating the connection",
        ),
    ] = None
    cert: typing.Optional[str] = pydantic.Field(default=None)
    """
    A value derived from decoding the signingCert. This should not be updated directly, instead update the signingCertificate to decode a new value for this field
    """

    idp_initiated: typing_extensions.Annotated[
        typing.Optional[IdpOptionsIdpInitiated],
        FieldMetadata(alias="idpInitiated"),
        pydantic.Field(alias="idpInitiated"),
    ] = None
    icon_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A URL pointing to an image file that represents your client application.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
