# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IdpUpdateBase(UniversalBaseModel):
    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identity provider name used on the login screen. Requires access_level to be 'full'
    """

    show_as_button: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD). Requires access_level to be 'full' or 'limited'
    """

    assign_membership_on_login: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the user will be made a member of the organization upon login. Requires access_level to be 'full' or 'limited'.
    """

    is_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True if the identity provider is enabled for the organization. Requires access_level to be 'full' or 'limited'
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
