# This file was auto-generated by Fern from our API Definition.

import typing

IdpProtocolBindingTypeEnum = typing.Union[
    typing.Literal[
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect", "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    ],
    typing.Any,
]
