# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .idp_samlp_options_request import IdpSamlpOptionsRequest
from .idp_update_base import IdpUpdateBase


class IdpSamlpUpdateRequest(IdpUpdateBase):
    """
    Identity provider specific options.  Requires access_level to be 'full'.
    """

    options: typing.Optional[IdpSamlpOptionsRequest] = pydantic.Field(default=None)
    """
    Identity provider specific options.  Requires access_level to be 'full'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
