# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IdpWaadOptionsResponse(UniversalBaseModel):
    tenant_domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    Your Azure AD domain name. You can find this on your Azure AD directory's overview page in the Microsoft Azure portal.
    """

    client_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for your registered Azure AD application.
    """

    icon_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A URL pointing to an image file that represents your client application.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
