# This file was auto-generated by Fern from our API Definition.

import typing

from .fed_metadata_xml import FedMetadataXml
from .idp_adfs_options_request_adfs_server import IdpAdfsOptionsRequestAdfsServer

IdpAdfsOptionsRequest = typing.Union[IdpAdfsOptionsRequestAdfsServer, FedMetadataXml]
