# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_oidc_options_type_enum import IdpOidcOptionsTypeEnum


class IdpOidcOptionsRequest(UniversalBaseModel):
    type: IdpOidcOptionsTypeEnum
    client_id: str = pydantic.Field()
    """
    The identifier given to you by your provider. Unique identifier for your registered application.
    """

    client_secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    Available if Back Channel is chosen earlier. The secret given to you by your provider and each provider manages this step differently.
    """

    discovery_url: str = pydantic.Field()
    """
    The URL where the OIDC Identity Provider publishes its OpenID Provider Configuration Information
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
