# This file was auto-generated by Fern from our API Definition.

import typing

from .idp_adfs_request import IdpAdfsRequest
from .idp_google_apps_request import IdpGoogleAppsRequest
from .idp_oidc_request import IdpOidcRequest
from .idp_okta_request import IdpOktaRequest
from .idp_ping_federate_request import IdpPingFederateRequest
from .idp_samlp_request import IdpSamlpRequest
from .idp_waad_request import IdpWaadRequest

IdpKnownRequest = typing.Union[
    IdpAdfsRequest,
    IdpGoogleAppsRequest,
    IdpOidcRequest,
    IdpOktaRequest,
    IdpPingFederateRequest,
    IdpSamlpRequest,
    IdpWaadRequest,
]
