# This file was auto-generated by Fern from our API Definition.

import typing

from .idp_adfs_options_response_adfs_server import IdpAdfsOptionsResponseAdfsServer
from .idp_adfs_options_response_fed_metadata_xml import IdpAdfsOptionsResponseFedMetadataXml

IdpAdfsOptionsResponse = typing.Union[IdpAdfsOptionsResponseAdfsServer, IdpAdfsOptionsResponseFedMetadataXml]
