# This file was auto-generated by Fern from our API Definition.

import typing

from .idp_adfs_response import IdpAdfsResponse
from .idp_google_apps_response import IdpGoogleAppsResponse
from .idp_oidc_response import IdpOidcResponse
from .idp_okta_response import IdpOktaResponse
from .idp_ping_federate_response import IdpPingFederateResponse
from .idp_samlp_response import IdpSamlpResponse
from .idp_waad_response import IdpWaadResponse

IdpKnownResponse = typing.Union[
    IdpAdfsResponse,
    IdpGoogleAppsResponse,
    IdpOidcResponse,
    IdpOktaResponse,
    IdpPingFederateResponse,
    IdpSamlpResponse,
    IdpWaadResponse,
]
