# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IdpScimTokenBase(UniversalBaseModel):
    token_id: str = pydantic.Field()
    """
    The token identifier.
    """

    scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The token's scopes.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The token's created at timestamp.
    """

    valid_until: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The token's valid until at timestamp (will not exist for non-expiring tokens).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
