# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .org_domain import OrgDomain


class ListOrganizationDomainsResponseContent(UniversalBaseModel):
    next: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pagination cursor for the next page of results
    """

    organization_domains: typing.List[OrgDomain]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
