# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .member_invitation import MemberInvitation


class ListMembersInvitationsResponseContent(UniversalBaseModel):
    next: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pagination cursor for the next page of results.
    """

    invitations: typing.Optional[typing.List[MemberInvitation]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
