# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .idp_options_idp_initiated import IdpOptionsIdpInitiated
from .idp_protocol_binding_type_enum import IdpProtocolBindingTypeEnum
from .idp_sign_alg_digest_type_enum import IdpSignAlgDigestTypeEnum
from .idp_sign_alg_type_enum import IdpSignAlgTypeEnum


class Manual(UniversalBaseModel):
    sign_in_endpoint: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="signInEndpoint"),
        pydantic.Field(alias="signInEndpoint", description="The endpoint URL for the IdP sign-in"),
    ] = None
    cert: typing.Optional[str] = pydantic.Field(default=None)
    """
    Signing certificate (encoded in PEM or CER) you retrieved from the IdP
    """

    sign_saml_request: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="signSAMLRequest"),
        pydantic.Field(
            alias="signSAMLRequest", description="When enabled, the SAML authentication request will be signed."
        ),
    ] = None
    signature_algorithm: typing_extensions.Annotated[
        typing.Optional[IdpSignAlgTypeEnum],
        FieldMetadata(alias="signatureAlgorithm"),
        pydantic.Field(alias="signatureAlgorithm"),
    ] = None
    digest_algorithm: typing_extensions.Annotated[
        typing.Optional[IdpSignAlgDigestTypeEnum],
        FieldMetadata(alias="digestAlgorithm"),
        pydantic.Field(alias="digestAlgorithm"),
    ] = None
    protocol_binding: typing_extensions.Annotated[
        typing.Optional[IdpProtocolBindingTypeEnum],
        FieldMetadata(alias="protocolBinding"),
        pydantic.Field(alias="protocolBinding"),
    ] = None
    binding_method: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bindingMethod"),
        pydantic.Field(
            alias="bindingMethod", description="Defines the specific HTTP binding used for sending SAML messages."
        ),
    ] = None
    idp_initiated: typing_extensions.Annotated[
        typing.Optional[IdpOptionsIdpInitiated],
        FieldMetadata(alias="idpInitiated"),
        pydantic.Field(alias="idpInitiated"),
    ] = None
    icon_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A URL pointing to an image file that represents your client application.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
