# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .idp_id import IdpId
from .invitation_id import InvitationId
from .member_invitation_invitee import MemberInvitationInvitee
from .member_invitation_inviter import MemberInvitationInviter
from .org_id import OrgId
from .org_member_role_id import OrgMemberRoleId


class MemberInvitation(UniversalBaseModel):
    id: typing.Optional[InvitationId] = None
    organization_id: typing.Optional[OrgId] = None
    inviter: typing.Optional[MemberInvitationInviter] = None
    invitee: typing.Optional[MemberInvitationInvitee] = None
    identity_provider_id: typing.Optional[IdpId] = None
    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The ISO 8601 formatted timestamp representing the creation time of the invitation.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The ISO 8601 formatted timestamp representing the expiration time of the invitation.
    """

    roles: typing.Optional[typing.List[OrgMemberRoleId]] = None
    invitation_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The invitation url to be sent to the invitee.
    """

    ticket_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the invitation ticket.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
