# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .org_domain_id import OrgDomainId
from .org_domain_name import OrgDomainName
from .org_domain_status_enum import OrgDomainStatusEnum
from .org_id import OrgId


class OrgDomain(UniversalBaseModel):
    id: OrgDomainId
    org_id: OrgId
    domain: OrgDomainName
    status: OrgDomainStatusEnum
    verification_txt: str = pydantic.Field()
    """
    Value used to verify the domain.
    """

    verification_host: str = pydantic.Field()
    """
    Stores the full domain where the TXT record should be added.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
