# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .org_third_party_client_access_enum import OrgThirdPartyClientAccessEnum


class OrgThirdPartyClientAccessConfig(UniversalBaseModel):
    """
    Configuration for third-party client access
    """

    default_value: OrgThirdPartyClientAccessEnum
    allowed_values: typing.List[OrgThirdPartyClientAccessEnum] = pydantic.Field()
    """
    Allowed third-party client access values
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
