# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization_access_level_enum import OrganizationAccessLevelEnum
from .organization_member_access_level_enum import OrganizationMemberAccessLevelEnum


class UserStore(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    User store Id
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User store name
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User store display name
    """

    access_level: typing.Optional[OrganizationAccessLevelEnum] = None
    member_access_level: typing.Optional[OrganizationMemberAccessLevelEnum] = pydantic.Field(default=None)
    """
    The Organization Member Access Level for this user store: what the Organization Admin can do to members authenticated via this connection.
    """

    is_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Is the user store enabled
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
