# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ValidationErrorDetail(UniversalBaseModel):
    detail: str = pydantic.Field()
    """
    A detailed description of the error.
    """

    field: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the invalid parameter.
    """

    pointer: typing.Optional[str] = pydantic.Field(default=None)
    """
    JSON Pointer that points to the exact location of the error in a JSON document being validated.
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specifies the source of the error (e.g., body, query, or header in an HTML message).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
