# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.create_identity_provider_request_content import CreateIdentityProviderRequestContent
from ...types.create_identity_provider_response_content import CreateIdentityProviderResponseContent
from ...types.get_identity_provider_response_content import GetIdentityProviderResponseContent
from ...types.idp_id import IdpId
from ...types.list_identity_providers_response_content import ListIdentityProvidersResponseContent
from ...types.update_identity_provider_request_content import UpdateIdentityProviderRequestContent
from ...types.update_identity_provider_response_content import UpdateIdentityProviderResponseContent
from .raw_client import AsyncRawIdentityProvidersClient, RawIdentityProvidersClient

if typing.TYPE_CHECKING:
    from .domains.client import AsyncDomainsClient, DomainsClient
    from .provisioning.client import AsyncProvisioningClient, ProvisioningClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class IdentityProvidersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIdentityProvidersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._domains: typing.Optional[DomainsClient] = None
        self._provisioning: typing.Optional[ProvisioningClient] = None

    @property
    def with_raw_response(self) -> RawIdentityProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIdentityProvidersClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListIdentityProvidersResponseContent:
        """
        Retrieve a list of all Identity Providers for this Organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIdentityProvidersResponseContent
            List of identity providers successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self, *, request: CreateIdentityProviderRequestContent, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateIdentityProviderResponseContent:
        """
        Create a new Identity Provider for this Organization.

        Parameters
        ----------
        request : CreateIdentityProviderRequestContent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdentityProviderResponseContent
            Identity provider successfully created.

        Examples
        --------
        from auth0 import Auth0, IdpOidcOptionsRequest, IdpOidcRequest

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.create(
            request=IdpOidcRequest(
                name="oidcIdp",
                strategy="oidc",
                domains=["mydomain.com"],
                display_name="OIDC IdP",
                show_as_button=True,
                assign_membership_on_login=False,
                is_enabled=True,
                options=IdpOidcOptionsRequest(
                    type="front_channel",
                    client_id="a8f3b2e7-5d1c-4f9a-8b0d-2e1c3a5b6f7d",
                    client_secret="KzQp2sVxR8nTgMjFhYcEWuLoIbDvUoC6A9B1zX7yWqFjHkGrP5sQdLmNp",
                    discovery_url="https://{yourDomain}/.well-known/openid-configuration",
                ),
            ),
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def get(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIdentityProviderResponseContent:
        """
        Retrieve details of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdentityProviderResponseContent
            Identity provider successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.get(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.get(idp_id, request_options=request_options)
        return _response.data

    def delete(self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete an Identity Provider specified by ID from this Organization. This will remove the association and delete the underlying Identity Provider. Members will no longer be able to authenticate using this Identity Provider.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.delete(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.delete(idp_id, request_options=request_options)
        return _response.data

    def update(
        self,
        idp_id: IdpId,
        *,
        request: UpdateIdentityProviderRequestContent,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateIdentityProviderResponseContent:
        """
        Update the details of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request : UpdateIdentityProviderRequestContent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateIdentityProviderResponseContent
            Identity provider successfully updated.

        Examples
        --------
        from auth0 import Auth0, IdpOidcOptionsRequest, IdpOidcUpdateRequest

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.update(
            idp_id="idp_id",
            request=IdpOidcUpdateRequest(
                display_name="OIDC IdP",
                show_as_button=True,
                assign_membership_on_login=False,
                is_enabled=True,
                options=IdpOidcOptionsRequest(
                    type="front_channel",
                    client_id="a8f3b2e7-5d1c-4f9a-8b0d-2e1c3a5b6f7d",
                    client_secret="KzQp2sVxR8nTgMjFhYcEWuLoIbDvUoC6A9B1zX7yWqFjHkGrP5sQdLmNp",
                    discovery_url="https://{yourDomain}/.well-known/openid-configuration",
                ),
            ),
        )
        """
        _response = self._raw_client.update(idp_id, request=request, request_options=request_options)
        return _response.data

    def update_attributes(
        self,
        idp_id: IdpId,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetIdentityProviderResponseContent:
        """
        Refresh the attribute mapping for an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.

        Parameters
        ----------
        idp_id : IdpId

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdentityProviderResponseContent
            Identity provider successfully retrieved.

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.update_attributes(
            idp_id="idp_id",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.update_attributes(idp_id, request=request, request_options=request_options)
        return _response.data

    def detach(self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove an Identity Provider specified by ID from this Organization. This only removes the association; the underlying Identity Provider is not deleted. Members will no longer be able to authenticate using this Identity Provider.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Auth0

        client = Auth0(
            token="YOUR_TOKEN",
        )
        client.organization.identity_providers.detach(
            idp_id="idp_id",
        )
        """
        _response = self._raw_client.detach(idp_id, request_options=request_options)
        return _response.data

    @property
    def domains(self):
        if self._domains is None:
            from .domains.client import DomainsClient  # noqa: E402

            self._domains = DomainsClient(client_wrapper=self._client_wrapper)
        return self._domains

    @property
    def provisioning(self):
        if self._provisioning is None:
            from .provisioning.client import ProvisioningClient  # noqa: E402

            self._provisioning = ProvisioningClient(client_wrapper=self._client_wrapper)
        return self._provisioning


class AsyncIdentityProvidersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIdentityProvidersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._domains: typing.Optional[AsyncDomainsClient] = None
        self._provisioning: typing.Optional[AsyncProvisioningClient] = None

    @property
    def with_raw_response(self) -> AsyncRawIdentityProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIdentityProvidersClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListIdentityProvidersResponseContent:
        """
        Retrieve a list of all Identity Providers for this Organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIdentityProvidersResponseContent
            List of identity providers successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self, *, request: CreateIdentityProviderRequestContent, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateIdentityProviderResponseContent:
        """
        Create a new Identity Provider for this Organization.

        Parameters
        ----------
        request : CreateIdentityProviderRequestContent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateIdentityProviderResponseContent
            Identity provider successfully created.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0, IdpOidcOptionsRequest, IdpOidcRequest

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.create(
                request=IdpOidcRequest(
                    name="oidcIdp",
                    strategy="oidc",
                    domains=["mydomain.com"],
                    display_name="OIDC IdP",
                    show_as_button=True,
                    assign_membership_on_login=False,
                    is_enabled=True,
                    options=IdpOidcOptionsRequest(
                        type="front_channel",
                        client_id="a8f3b2e7-5d1c-4f9a-8b0d-2e1c3a5b6f7d",
                        client_secret="KzQp2sVxR8nTgMjFhYcEWuLoIbDvUoC6A9B1zX7yWqFjHkGrP5sQdLmNp",
                        discovery_url="https://{yourDomain}/.well-known/openid-configuration",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def get(
        self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIdentityProviderResponseContent:
        """
        Retrieve details of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdentityProviderResponseContent
            Identity provider successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.get(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(idp_id, request_options=request_options)
        return _response.data

    async def delete(self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete an Identity Provider specified by ID from this Organization. This will remove the association and delete the underlying Identity Provider. Members will no longer be able to authenticate using this Identity Provider.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.delete(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(idp_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        idp_id: IdpId,
        *,
        request: UpdateIdentityProviderRequestContent,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateIdentityProviderResponseContent:
        """
        Update the details of an Identity Provider specified by ID for this Organization.

        Parameters
        ----------
        idp_id : IdpId

        request : UpdateIdentityProviderRequestContent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateIdentityProviderResponseContent
            Identity provider successfully updated.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0, IdpOidcOptionsRequest, IdpOidcUpdateRequest

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.update(
                idp_id="idp_id",
                request=IdpOidcUpdateRequest(
                    display_name="OIDC IdP",
                    show_as_button=True,
                    assign_membership_on_login=False,
                    is_enabled=True,
                    options=IdpOidcOptionsRequest(
                        type="front_channel",
                        client_id="a8f3b2e7-5d1c-4f9a-8b0d-2e1c3a5b6f7d",
                        client_secret="KzQp2sVxR8nTgMjFhYcEWuLoIbDvUoC6A9B1zX7yWqFjHkGrP5sQdLmNp",
                        discovery_url="https://{yourDomain}/.well-known/openid-configuration",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(idp_id, request=request, request_options=request_options)
        return _response.data

    async def update_attributes(
        self,
        idp_id: IdpId,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetIdentityProviderResponseContent:
        """
        Refresh the attribute mapping for an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.

        Parameters
        ----------
        idp_id : IdpId

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIdentityProviderResponseContent
            Identity provider successfully retrieved.

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.update_attributes(
                idp_id="idp_id",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_attributes(idp_id, request=request, request_options=request_options)
        return _response.data

    async def detach(self, idp_id: IdpId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove an Identity Provider specified by ID from this Organization. This only removes the association; the underlying Identity Provider is not deleted. Members will no longer be able to authenticate using this Identity Provider.

        Parameters
        ----------
        idp_id : IdpId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncAuth0

        client = AsyncAuth0(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.identity_providers.detach(
                idp_id="idp_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.detach(idp_id, request_options=request_options)
        return _response.data

    @property
    def domains(self):
        if self._domains is None:
            from .domains.client import AsyncDomainsClient  # noqa: E402

            self._domains = AsyncDomainsClient(client_wrapper=self._client_wrapper)
        return self._domains

    @property
    def provisioning(self):
        if self._provisioning is None:
            from .provisioning.client import AsyncProvisioningClient  # noqa: E402

            self._provisioning = AsyncProvisioningClient(client_wrapper=self._client_wrapper)
        return self._provisioning
